src/Entity/Media.php
<?php
declare(strict_types=1);

namespace Nakima\MediaBundle\Entity;

/**
 * @author xgonzalez@nakima.es
 */

use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\MappedSuperclass;
use MediaBundle\Entity\MediaProvider;
use Nakima\ControllerBundle\Utils\SymfonyHelper;
use Nakima\CoreBundle\Entity\BaseEntity;
use Nakima\CoreBundle\Utils\Doctrine;
use Nakima\CoreBundle\Utils\Symfony;
use Symfony\Component\HttpFoundation\File\File;

/**
 * @MappedSuperclass(repositoryClass="Nakima\MediaBundle\Repository\MediaRepository")
 */
class Media extends BaseEntity
{

    const METADATA_EMPTY = "{}";
    //const PROVIDERS = ['file', 'image', 'video', 'tumblr',  'youtube', 'vimeo', 'imgur'];

    /**
     * @var string
     * @Column(type="string", length=128)
     */
    protected $path;

    /**
     * @var MediaProvider
     * @ManyToOne(targetEntity="MediaBundle\Entity\MediaProvider")
     * @JoinColumn(name="mediaprovider_id", referencedColumnName="id")
     */
    protected $provider;

    /**
     * @var array
     * @Column(type="json")
     */
    protected $metadata;

    /**
     * @var array
     * @Column(type="json_save")
     */
    protected $privateMetadata;

    /**
     * @var int
     * @Column(type="integer")
     */
    protected $size;

    /**
     * @var string
     * @Column
     */
    protected $mime;

    /**
     * @var string
     * @Column(length=128)
     */
    protected $name;

    protected $file;

    protected $link;

    /**************************************************************************
     * Custom Functions                                                       *
     **************************************************************************/

    public function __toArray(array $options = []): array
    {
        $ret = parent::__toArray($options);

        $ret['path']         = $this->getPath();
        $ret['name']         = $this->getName();
        $ret['fullpath']     = $this->getFullpath();
        $ret['provider']     = $this->getProvider();
        $ret['mime']         = $this->getMime();
        $ret['metadata']     = $this->getMetadata();
        $ret['size']         = $this->getSize();
        $ret['downloadLink'] = $this->getDownloadLink();

        return $ret;
    }

    public function __construct()
    {
        $this->provider = 'provider.file';
        $this->setMetadata([]);
        $this->setPrivateMetadata([]);

        $this->setPath("/bundles/nakimamedia/img");
        $this->setProvider(\MediaBundle\Entity\MediaProvider::IMAGE());
        $this->setName('default.jpg');
        $this->setMime('image/jpeg');
        $this->setSize(7592);
    }

    public function __toString()
    {
        return $this->name;
    }

    public function getDownloadLink(string $filename = null): ?string
    {
        if (!$filename) {
            $filename = $this->getName();
        }

        return Symfony::get('router')->generate(
            "nakima_media_media_download",
            ['id' => $this->id, 'filename' => $filename],
            0
        );
    }

    public function getPath(): string
    {
        return $this->path;
    }

    public function setPath(string $path)
    {
        $this->path = $path;
    }

    public function getProvider(): ?MediaProvider
    {
        return $this->provider;
    }

    public function setProvider(?MediaProvider $provider)
    {
        $this->provider = $provider;
    }

    /**
     * @return array
     */
    public function getMetadata(): array
    {
        return $this->metadata;
    }

    /**
     * @param array $metadata
     */
    public function setMetadata(array $metadata)
    {
        $this->metadata = $metadata;
    }

    /**
     * @return array
     */
    public function getPrivateMetadata(): array
    {
        return $this->privateMetadata;
    }

    /**
     * @param array $privateMetadata
     */
    public function setPrivateMetadata(array $privateMetadata)
    {
        $this->privateMetadata = $privateMetadata;
    }

    public function getSize(): int
    {
        return $this->size;
    }

    public function setSize(int $size)
    {
        $this->size = $size;
    }

    public function getMime(): string
    {
        return $this->mime;
    }

    public function setMime(string $mime)
    {
        $this->mime = $mime ?? 'unknown';
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name)
    {
        $this->name = $name;
    }

    public function deleteFile()
    {

        $file = $this->getPrivateMetadata()["dir"];

        if (file_exists($file)) {
            unlink($file);
        }
    }

    public function upload(string $folder, string $filename, string $dir = null)
    {

        if (!$dir) {
            $dir = $folder;
        }

        if (!$this->getFile()) {
            return false;
        }

        $root = Symfony::getRoot();
        $this->setName($filename);

        $meta             = $this->getPrivateMetadata();
        $meta['dir']      = "$folder";
        $meta['filename'] = "$filename";
        $meta['full']     = "$folder/$filename";
        $this->setPrivateMetadata($meta);

        $this->getFile()->move(
            "$root/$folder",
            $filename
        );
    }

    public function getFile(): ?File
    {
        return $this->file;
    }

    public function setFile(File $file)
    {
        if ($file) {
            $this->file = $file;

            $this->setMime($file->getMimeType());
            $this->setProvider(
                \MediaBundle\Entity\MediaProvider::loadFromMime($this->getMime())
            );
            $this->setSize($file->getSize());
            $this->setMetadata([]);
            $this->setPrivateMetadata([]);
        }

        return $this;
    }

    public function getCompletePath(): string
    {
        return $this->path . "/" . $this->name;
    }

    public function getFullpath(): string
    {
        return "$this->path/$this->name";
    }

}

src/Form/DataTransformer/FileToMediaTransformer.php
<?php
declare(strict_types=1);
namespace Nakima\MediaBundle\Form\DataTransformer;

/**
 * @author xgc1986 < xgc1986@gmail.com >
 * @author Adrià Llaudet Planas < allaudet@nakima.es >
 */

use Nakima\CoreBundle\Utils\Symfony;
use Nakima\Utils\String\Text;
use Symfony\Component\Form\DataTransformerInterface;

class FileToMediaTransformer implements DataTransformerInterface
{

    protected $mediaProviderService;
    protected $entity;
    protected $field;
    protected $path;
    protected $name;
    protected $provider;
    protected $public;

    public function __construct($entity, $field, $path, $name, $provider, $public, $mediaProviderService)
    {
        $this->mediaProviderService = $mediaProviderService;
        $this->entity = $entity;
        $this->field = $field;
        $this->path = $path;
        $this->name = $name;
        $this->provider = $provider;
        $this->public = $public;

        if (!$this->name) {
            $this->name = Text::rstr(12);
        }
    }

    public function transform($file)
    {
        return $file;
    }

    public function reverseTransform($file)
    {
        if (!$file) {
            return $this->entity->get($this->field);
        }

        if (!$file->getFile()) {
            return $this->entity->get($this->field);
        }

        $id = $this->name;
        $file = $file->getFile();

        $root = Symfony::getRoot();
        $extension = ".".$file->guessExtension();
        $path = $this->path;
        $filename = $id.$extension;

        $media = $this->mediaProviderService->buildMedia($file, $this->provider, $this->entity->get($this->field));
        $media->setPath("/uploads$path");
        $media->setName($filename);

        if ($this->public) {
            $media->upload(
                "$root/web/uploads$path",
                $filename
            );
        } else {
            $media->upload(
                "$root/uploads$path",
                $filename
            );
        }

        return $media;
    }
}

src/Form/Type/File2Type.php
<?php
declare(strict_types=1);
namespace Nakima\MediaBundle\Form\Type;

/**
 * xgc1986 < xgc1986@gmail.com >
 */

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class File2Type extends AbstractType
{

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => null,
                'class' => 'MediaBundle\Entity\Media',
                'compound' => false,
                'route' => 'nakima_media_media',
            ]
        );

        //$resolver->setDefined(['route']);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }

    public function getParent()
    {
        return EntityType::class;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['route'] = $options['route'];
    }
}

src/Form/Type/GalleryType.php
<?php
declare(strict_types=1);
namespace Nakima\MediaBundle\Form\Type;

/**
 * xgc1986 < xgc1986@gmail.com >
 */

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class GalleryType extends AbstractType
{

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'MediaBundle\Entity\Gallery',
                'compound' => true,
            ]
        );
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('file', 'hidden');
        $builder->add('media', 'hidden');
    }

    public function getParent()
    {
        return FileType::class;
    }
}

src/Form/Type/Image2Type.php
<?php
declare(strict_types=1);
namespace Nakima\MediaBundle\Form\Type;

/**
 * xgc1986 < xgc1986@gmail.com >
 */

use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Image2Type extends AbstractType
{

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => null,
                'class' => 'MediaBundle\Entity\Media',
                'compound' => false,
                'route' => 'nakima_media_media',
            ]
        );

        //$resolver->setDefined(['route']);
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
    }

    public function getParent()
    {
        return EntityType::class;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['route'] = $options['route'];
    }
}

src/Form/Type/MediaType.php
<?php
declare(strict_types=1);
namespace Nakima\MediaBundle\Form\Type;

/**
 * xgc1986 < xgc1986@gmail.com >
 */


use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MediaType extends AbstractType
{

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'MediaBundle\Entity\Media',
                'compound' => true,
            ]
        );
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('file');
    }

    public function getParent()
    {
        return FileType::class;
    }
}

src/Resources/views/Form/fields.html.twig
{# app/Resources/views/form/fields.html.twig #}
{% block file2_widget %}
    <div class="dynamic-file" id="{{ id }}_file_form">
      <label for="{{ id }}_file"> <a class="btn btn-default">{% trans from "nakima_media" %}upload_file{% endtrans %}</a></label>
      <input class="dynamic-file-input" id="{{ id }}_file" type="file" class="form-control" style="display:none" />
      {% if data %}
        <div class="ghost-link dynamic-file-link">
          <span><a target="_blank" class="btn btn-link" href="{{ data.downloadLink }}"><i class="fa fa-download" >&nbsp;</i>{% trans from "nakima_media" %}download{% endtrans %}</a></span>
          <span><a target="_blank" class="btn btn-link" href="#" onclick="removeFile(event, this)"><i class="fa fa-close">&nbsp;</i>{% trans from "nakima_media" %}delete{% endtrans %}</a></span>
        </div>
        <input class="dynamic-file-hidden" type="hidden" value="{{ data.id }}">
      {% else %}
        <div class="ghost ghost-link dynamic-file-link">
          <span><a target="_blank" class="btn btn-link" href="#"><i class="fa fa-download">&nbsp;</i>{% trans from "nakima_media" %}download{% endtrans %}</a></span>
          <span><a target="_blank" class="btn btn-link" href="#" onclick="removeFile(event, this)"><i class="fa fa-close">&nbsp;</i>{% trans from "nakima_media" %}delete{% endtrans %}</a></span>
        </div>
        <input class="dynamic-file-hidden" type="hidden" value="">
      {% endif %}
    </div>


    <script>
    _id("{{ id }}_file_form").addEventListener( 'change', function( event ) {
        var file = event.target.files[0];
        var path = "{{ url(form.vars.route) }}";
        if (file) {
            if (file.size < {{ _maximumUploadSize() }}) {
                upload(path, file, "{{ full_name }}", event.target.parentNode);
            }
        }
        event.target.value = "";
    });

    function removeFile(event, element) {
      element = element.parentNode.parentNode.parentNode;
      event.preventDefault();

      element._class("ghost-link")[0].classList.add("ghost");

      var hidden = element._class("dynamic-file-hidden")[0];
      hidden.value = "";
    }

    function upload(path, file, name, element) {
        var xhr = new XMLHttpRequest();
        xhr.withCredentials = true;
        xhr.upload.addEventListener('progress', function(event) {
          var pc = parseInt(100 - (event.loaded / event.total * 100));
          if (pc) {
            element._tag('label')[0]._tag('a')[0].innerText = '{% trans from "nakima_media" %}delete{% endtrans %}' + " ( " + pc + "% )";
            //console.log(pc);
          }
        });
        xhr.onreadystatechange = function(event) {
          if (xhr.readyState == 4) {
            //bar.style.width = "100%";
            if (xhr.status == 200) {
              var media = JSON.parse(xhr.response);

              element._class("dynamic-file-input")[0].value = "";
              var links =element._class("ghost-link")[0];
              links.classList.remove('ghost');

              links._tag('a')[0].href = media.media.downloadLink;

              var hidden = element._class("dynamic-file-hidden")[0];
              hidden.value = media.media.id;
              hidden.name = name;

              element._tag('label')[0]._tag('a')[0].innerText = '{% trans from "nakima_media" %}delete{% endtrans %}';

            } else {
              console.log('error');
            }
          }
        };

        var formData = new FormData();
        formData.append("media", file);
        xhr.open("POST", path, true);
        xhr.send(formData);
      }
    </script>
{% endblock %}

{# app/Resources/views/form/fields.html.twig #}
{% block image2_widget %}
    <div class="dynamic-file" id="{{ id }}_file_form">
      <label for="{{ id }}_file"> <a class="btn btn-default">{% trans from "nakima_media" %}upload_file{% endtrans %}</a></label>
      <input class="dynamic-file-input" id="{{ id }}_file" type="file" class="form-control" style="display:none" onchange="updateUserImage(event)"/>
      {% if data %}
        <div class="ghost-link dynamic-file-link">
          <img class="img-responsive" id="{{ id }}_file_image" src="{{ data.downloadLink }}" height="200px" style="height:200px">
          <span><a target="_blank" class="btn btn-link" href="{{ data.downloadLink }}"><i class="fa fa-download" >&nbsp;</i>{% trans from "nakima_media" %}download{% endtrans %}</a></span>
          <span><a target="_blank" class="btn btn-link" href="#" onclick="removeFile(event, this)"><i class="fa fa-close">&nbsp;</i>{% trans from "nakima_media" %}delete{% endtrans %}</a></span>
        </div>
        <input class="dynamic-file-hidden" type="hidden" name="{{ full_name }}" value="{{ data.id }}" onchange="updateUserImage(event, this)">
      {% else %}
        <div class="ghost ghost-link dynamic-file-link">
          <img class="img-responsive" id="{{ id }}_file_image" src="{url}" height="200px" style="height:200px">
          <span><a target="_blank" class="btn btn-link" href="#"><i class="fa fa-download">&nbsp;</i>{% trans from "nakima_media" %}download{% endtrans %}</a></span>
          <span><a target="_blank" class="btn btn-link" href="#" onclick="removeFile(event, this)"><i class="fa fa-close">&nbsp;</i>{% trans from "nakima_media" %}delete{% endtrans %}</a></span>
        </div>
        <input class="dynamic-file-hidden" type="hidden" name="{{ full_name }}" value="" onchange="updateUserImage(event, this)">
      {% endif %}
    </div>


    <script>
    function updateUserImage( event, dom ) {
        var file = event.target.files[0];
        var path = "{{ url(form.vars.route) }}";

        if (file) {
            if (file.size < {{ _maximumUploadSize() }}) {
                upload(path, file, "{{ full_name }}", event.target.parentNode);
            }
        }
        event.target.value = "";
    };

    function removeFile(event, element) {
      element = element.parentNode.parentNode.parentNode;
      event.preventDefault();

      element._class("ghost-link")[0].classList.add("ghost");

      var hidden = element._class("dynamic-file-hidden")[0];
      hidden.value = "";
    }

    function upload(path, file, name, element) {

        var xhr = new XMLHttpRequest();
        xhr.withCredentials = true;
        xhr.upload.addEventListener('progress', function(event) {
          var pc = parseInt(100 - (event.loaded / event.total * 100));
          if (pc) {
            element._tag('label')[0]._tag('a')[0].innerText = '{% trans from "nakima_media" %}upload_file{% endtrans %}' + " ( " + pc + "% )";
          }
        });
        xhr.onreadystatechange = function(event) {
          if (xhr.readyState == 4) {
            //bar.style.width = "100%";
            if (xhr.status == 200) {

              var media = JSON.parse(xhr.response);
              element._put("url", media.media.downloadLink);
              element._class("dynamic-file-input")[0].value = "";
              var links = element._class("ghost-link")[0];
              links.classList.remove('ghost');

              element._tag('img')[0].src = media.media.downloadLink;

              links._tag('a')[0].href = media.media.downloadLink;

              var hidden = element._class("dynamic-file-hidden")[0];
              hidden.value = media.media.id;

              element._tag('label')[0]._tag('a')[0].innerText = '{% trans from "nakima_media" %}upload_file{% endtrans %}';
            } else {
              console.log('error');
            }
          }
        };

        var formData = new FormData();
        formData.append("media", file);
        xhr.open("POST", path, true);
        xhr.send(formData);
      }
    </script>
{% endblock %}

{% block media_widget %}
    {% spaceless %}
        <style>
            .dont-break-out {
              /* These are technically the same, but use both */
              overflow-wrap: break-word;
              word-wrap: break-word;

              -ms-word-break: break-all;
              /* This is the dangerous one in WebKit, as it breaks things wherever */
              word-break: break-all;
              /* Instead use this non-standard one: */
              word-break: break-word;

              /* Adds a hyphen where the word breaks, if supported (No Blink) */
              -ms-hyphens: auto;
              -moz-hyphens: auto;
              -webkit-hyphens: auto;
              hyphens: auto;
            }
        </style>
        <input id="{{ id }}_file" type="file" class="form-control" name="{{ full_name }}[file]" />

        <div class="row" style="margin-top:10px">
            <div class="col-md-4">
                <img id="{{ id }}_preview" class="img-responsive" src="{% if data %}{{ data.completePath }}{% endif %}">
            </div>
            <div class="col-md-6">
                <table  class="table table-responsive table-bordered" >
                    <tbody>
                        <tr><td class="dont-break-out col-md-6"><b>Nombre de fichero: </b></td><td class="dont-break-out col-md-6" id="{{ id }}_name">{% if data %}{{ data.name }}{% endif %}</td></tr>
                        <tr><td class="dont-break-out col-md-6"><b>Tamaño: </b></td><td class="dont-break-out col-md-6" id="{{ id }}_size">{% if data %}{{ data.size }}{% endif %}</td></tr>
                        <tr><td class="dont-break-out col-md-6"><b>Tipo: </b></td><td class="dont-break-out col-md-6" id="{{ id }}_type">{% if data %}{{ data.mime }}{% endif %}</td></tr>
                    </tbody>
                </table>
            </div>
        </div>
        <script>

            function getSize(s) {
                var values = ["B", "KB", "GB", "TB", "PB", "PB", "EB", "ZB", "YB"];
                var index = 0;

                while (s >= 1024) {
                    index++;
                    s = s / 1024;
                }

                return Math.round(s * 100) / 100 + " " + values[index];
            }

            (function () {
                var input = _id('{{ id }}_file');
                var preview = _id('{{ id }}_preview');

                input.addEventListener('change', function(event) {
                    var file = event.target.files[0];
                    if (file) {
                        _id('{{ id }}_name').innerHTML = file.name;

                        var size = getSize(file.size);
                        _id('{{ id }}_size').innerHTML = size;
                        _id('{{ id }}_type').innerHTML = file.type;
                        if (file.type.startsWith("image/")) {
                            if (file.size > 2000000) {
                                input.data = "";
                                alert("La imatge és massa gran");
                            } else {
                                var reader = new FileReader();
                                reader.readAsDataURL(file);
                                reader.addEventListener('load', function(event) {
                                    preview.src = event.target.result;
                                });
                            }
                        } else {
                        }
                    }
                }, false)
            })();
        </script>
    {% endspaceless %}
{% endblock %}